name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  test-lint-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run Lint
        run: npm run format:check

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Passe diesen Pfad an, falls dein Build-Ordner anders heißt
