name: Development Workflow

on:
  push:
    branches:
      - development

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Run Lint
        run: npm run format:check
